CREATE DATABASE cursodb;

\c cursodb;

CREATE TABLE instrutor (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    experiencia VARCHAR(255) NOT NULL
);

CREATE TABLE curso (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    descricao TEXT NOT NULL,
    instrutor_id INTEGER REFERENCES instrutor(id) ON DELETE CASCADE,
    photo TEXT
);

INSERT INTO instrutor (name, email, experiencia) VALUES 
('Dra. Luiza Nicoluci', 'lu.nicoluci@gmail.com', 'Especialista em Linguística'),
('Dra. Heloísa Damazio', 'helo.damazio@gmail.com', 'Cirurgiã Geral'),
('Dra. Clara Rabello', 'clara.rabello@gmail.com', 'Especialista em Pediatria'),
('Dra. Ana Júlia Demattei', 'anaju.demattei@gmail.com', 'Especialista em Reabilitação Neurológica'),
('Dr. Rafael Souza', 'rafael.souza@gmail.com', 'Psicólogo especialista em Neuropsicologia'),
('Dr. Pedro Lima', 'pedro.lima@gmail.com', 'Terapeuta Ocupacional em Neurologia Infantil'),
('Dr. Lucas Almeida', 'lucas.almeida@gmail.com', 'Psicólogo em Reabilitação Cognitiva'),
('Dra. Mariana Torres', 'mariana.torres@gmail.com', 'Fonoaudióloga em Linguagem Infantil'),
('Dr. Felipe Martins', 'felipe.martins@gmail.com', 'Fisioterapeuta em Reabilitação Neurológica'),
('Dra. Camila Rocha', 'camila.rocha@gmail.com', 'Fonoaudióloga em Disfagia'),
('Dr. Gustavo Melo', 'gustavo.melo@gmail.com', 'Psicólogo em ABA'),
('Dra. Bianca Freitas', 'bianca.freitas@gmail.com', 'Terapeuta Ocupacional em Paralisia Cerebral'),
('Dr. André Pereira', 'andre.pereira@gmail.com', 'Fisioterapeuta em Doenças Neuromusculares'),
('Dra. Renata Gomes', 'renata.gomes@gmail.com', 'Fonoaudióloga em Disfagia Neurológica'),
('Dr. Bruno Martins', 'bruno.martins@gmail.com', 'Psicólogo em Neurodesenvolvimento'),
('Dra. Juliana Torres', 'juliana.torres@gmail.com', 'Terapeuta Ocupacional em Reabilitação Cognitiva'),
('Dr. Eduardo Barros', 'eduardo.barros@gmail.com', 'Fisioterapeuta em AVC'),
('Dra. Patrícia Ramos', 'patricia.ramos@gmail.com', 'Fonoaudióloga em Motricidade Orofacial'),
('Dr. Henrique Lopes', 'henrique.lopes@gmail.com', 'Psicólogo em Transtornos do Neurodesenvolvimento'),
('Dra. Larissa Faria', 'larissa.faria@gmail.com', 'Terapeuta Ocupacional em Lesão Cerebral'),
('Dr. Marcelo Pinto', 'marcelo.pinto@gmail.com', 'Fisioterapeuta em Reabilitação Motora'),
('Dra. Aline Cardoso', 'aline.cardoso@gmail.com', 'Fonoaudióloga em Processamento Auditivo Central'),
('Dr. Rodrigo Vieira', 'rodrigo.vieira@gmail.com', 'Psicólogo em Intervenção ABA'),
('Dra. Priscila Teixeira', 'priscila.teixeira@gmail.com', 'Terapeuta Ocupacional em Deficiência Intelectual'),
('Dr. Daniel Monteiro', 'daniel.monteiro@gmail.com', 'Fisioterapeuta em Reabilitação Infantil'),
('Dra. Simone Batista', 'simone.batista@gmail.com', 'Fonoaudióloga em Apraxia de Fala'),
('Dr. Alexandre Nunes', 'alexandre.nunes@gmail.com', 'Psicólogo em Neurociências'),
('Dra. Tatiane Pires', 'tatiane.pires@gmail.com', 'Terapeuta Ocupacional em TEA'),
('Dr. Leandro Castro', 'leandro.castro@gmail.com', 'Fisioterapeuta em Reabilitação Pós-AVC'),
('Dra. Gabriela Ribeiro', 'gabriela.ribeiro@gmail.com', 'Fonoaudióloga em Disartria'),
('Dr. Vinícius Fernandes', 'vinicius.fernandes@gmail.com', 'Psicólogo em Reabilitação Neuropsicológica'),
('Dra. Rafaela Oliveira', 'rafaela.oliveira@gmail.com', 'Terapeuta Ocupacional em Reabilitação Física'),
('Dr. Matheus Carvalho', 'matheus.carvalho@gmail.com', 'Fisioterapeuta em Doenças Degenerativas'),
('Dra. Letícia Mendes', 'leticia.mendes@gmail.com', 'Fonoaudióloga em Voz Neurológica'),
('Dr. Fábio Santos', 'fabio.santos@gmail.com', 'Psicólogo em Estimulação Cognitiva'),
('Dra. Vanessa Moreira', 'vanessa.moreira@gmail.com', 'Terapeuta Ocupacional em Inclusão Escolar'),
('Dr. Tiago Rezende', 'tiago.rezende@gmail.com', 'Fisioterapeuta em Reabilitação Vestibular'),
('Dra. Carolina Lopes', 'carolina.lopes@gmail.com', 'Fonoaudióloga em Deglutição'),
('Dr. Igor Martins', 'igor.martins@gmail.com', 'Psicólogo em Neuropsicopedagogia'),
('Dra. Amanda Souza', 'amanda.souza@gmail.com', 'Terapeuta Ocupacional em Reabilitação Visual'),
('Dr. Murilo Dias', 'murilo.dias@gmail.com', 'Fisioterapeuta em Reabilitação Geriátrica'),
('Dra. Sabrina Lima', 'sabrina.lima@gmail.com', 'Fonoaudióloga em Linguagem Infantil'),
('Dr. Otávio Rocha', 'otavio.rocha@gmail.com', 'Psicólogo em Neurociência do Comportamento'),
('Dra. Mônica Silva', 'monica.silva@gmail.com', 'Terapeuta Ocupacional em Reabilitação Neurológica'),
('Dr. Rafael Gomes', 'rafael.gomes@gmail.com', 'Fisioterapeuta em Reabilitação Cognitiva'),
('Dra. Paula Duarte', 'paula.duarte@gmail.com', 'Fonoaudióloga em Comunicação Alternativa'),
('Dr. João Pedro', 'joao.pedro@gmail.com', 'Psicólogo em Neuropsicologia Infantil'),
('Dra. Isabela Costa', 'isabela.costa@gmail.com', 'Terapeuta Ocupacional em Reabilitação Motora'),
('Dr. Guilherme Ramos', 'guilherme.ramos@gmail.com', 'Fisioterapeuta em Reabilitação Vestibular'),
('Dra. Bruna Fernandes', 'bruna.fernandes@gmail.com', 'Fonoaudióloga em Disfemia'),
('Dr. Diego Teixeira', 'diego.teixeira@gmail.com', 'Psicólogo em Reabilitação Cognitiva'),
('Dra. Patrícia Souza', 'patricia.souza@gmail.com', 'Terapeuta Ocupacional em Reabilitação Infantil'),
('Dr. Caio Almeida', 'caio.almeida@gmail.com', 'Fisioterapeuta em Reabilitação Vestibular'),
('Dra. Flávia Nunes', 'flavia.nunes@gmail.com', 'Fonoaudióloga em Disartria Neurológica'),
('Dr. Sérgio Lopes', 'sergio.lopes@gmail.com', 'Psicólogo em Neuropsicologia Clínica'),
('Dra. Paula Martins', 'paula.martins@gmail.com', 'Terapeuta Ocupacional em Reabilitação Física'),
('Dr. Bruno Souza', 'bruno.souza@gmail.com', 'Fisioterapeuta em Reabilitação Motora Infantil'),
('Dra. Renata Lima', 'renata.lima@gmail.com', 'Fonoaudióloga em Apraxia de Fala'),
('Dr. Felipe Rocha', 'felipe.rocha@gmail.com', 'Psicólogo em ABA para Autismo'),
('Dra. Juliana Barros', 'juliana.barros@gmail.com', 'Terapeuta Ocupacional em Saúde Mental'),
('Dr. André Ramos', 'andre.ramos@gmail.com', 'Fisioterapeuta em Doenças Degenerativas'),
('Dra. Camila Fernandes', 'camila.fernandes@gmail.com', 'Fonoaudióloga em Voz Neurológica'),
('Dr. Gustavo Cardoso', 'gustavo.cardoso@gmail.com', 'Psicólogo em Estimulação Cognitiva'),
('Dra. Bianca Ribeiro', 'bianca.ribeiro@gmail.com', 'Terapeuta Ocupacional em TEA'),
('Dr. Eduardo Castro', 'eduardo.castro@gmail.com', 'Fisioterapeuta em Reabilitação Pós-AVC'),
('Dra. Vanessa Mendes', 'vanessa.mendes@gmail.com', 'Fonoaudióloga em Processamento Auditivo Central'),
('Dr. Leandro Teixeira', 'leandro.teixeira@gmail.com', 'Psicólogo em Neurodesenvolvimento Infantil'),
('Dra. Tatiane Silva', 'tatiane.silva@gmail.com', 'Terapeuta Ocupacional em Lesão Cerebral'),
('Dr. Henrique Barros', 'henrique.barros@gmail.com', 'Fisioterapeuta em Reabilitação Geriátrica'),
('Dra. Gabriela Costa', 'gabriela.costa@gmail.com', 'Fonoaudióloga em Comunicação Alternativa'),
('Dr. Matheus Santos', 'matheus.santos@gmail.com', 'Psicólogo em Neurociência do Comportamento'),
('Dra. Rafaela Faria', 'rafaela.faria@gmail.com', 'Terapeuta Ocupacional em Reabilitação Cognitiva'),
('Dr. Rodrigo Martins', 'rodrigo.martins@gmail.com', 'Fisioterapeuta em Reabilitação Infantil'),
('Dra. Aline Souza', 'aline.souza@gmail.com', 'Fonoaudióloga em Motricidade Orofacial'),
('Dr. Daniel Vieira', 'daniel.vieira@gmail.com', 'Psicólogo em Transtornos do Neurodesenvolvimento'),
('Dra. Simone Rocha', 'simone.rocha@gmail.com', 'Terapeuta Ocupacional em Deficiência Intelectual'),
('Dr. Alexandre Lima', 'alexandre.lima@gmail.com', 'Fisioterapeuta em Reabilitação Neurológica'),
('Dra. Priscila Nunes', 'priscila.nunes@gmail.com', 'Fonoaudióloga em Disfemia'),
('Dr. Murilo Ramos', 'murilo.ramos@gmail.com', 'Psicólogo em Reabilitação Cognitiva'),
('Dra. Sabrina Teixeira', 'sabrina.teixeira@gmail.com', 'Terapeuta Ocupacional em Reabilitação Visual'),
('Dr. Otávio Fernandes', 'otavio.fernandes@gmail.com', 'Fisioterapeuta em Reabilitação Cognitiva'),
('Dra. Mônica Duarte', 'monica.duarte@gmail.com', 'Fonoaudióloga em Linguagem Infantil'),
('Dr. Rafael Batista', 'rafael.batista@gmail.com', 'Psicólogo em Neuropsicopedagogia'),
('Dra. Paula Rezende', 'paula.rezende@gmail.com', 'Terapeuta Ocupacional em Saúde Mental Infantil'),
('Dr. João Costa', 'joao.costa@gmail.com', 'Fisioterapeuta em Reabilitação Vestibular'),
('Dra. Isabela Almeida', 'isabela.almeida@gmail.com', 'Fonoaudióloga em Deglutição'),
('Dr. Guilherme Silva', 'guilherme.silva@gmail.com', 'Psicólogo em ABA para Deficiência Intelectual'),
('Dra. Bruna Ramos', 'bruna.ramos@gmail.com', 'Terapeuta Ocupacional em Inclusão Escolar'),
('Dr. Diego Cardoso', 'diego.cardoso@gmail.com', 'Fisioterapeuta em Reabilitação Motora'),
('Dra. Patrícia Fernandes', 'patricia.fernandes@gmail.com', 'Fonoaudióloga em Voz Neurológica'),
('Dr. Caio Martins', 'caio.martins@gmail.com', 'Psicólogo em Estimulação Cognitiva'),
('Dra. Flávia Souza', 'flavia.souza@gmail.com', 'Terapeuta Ocupacional em TEA'),
('Dr. Sérgio Rocha', 'sergio.rocha@gmail.com', 'Fisioterapeuta em Reabilitação Pós-AVC'),
('Dra. Paula Lopes', 'paula.lopes@gmail.com', 'Fonoaudióloga em Processamento Auditivo Central'),
('Dr. Bruno Nunes', 'bruno.nunes@gmail.com', 'Psicólogo em Neurodesenvolvimento'),
('Dra. Renata Barros', 'renata.barros@gmail.com', 'Terapeuta Ocupacional em Lesão Cerebral'),
('Dr. Felipe Mendes', 'felipe.mendes@gmail.com', 'Fisioterapeuta em Reabilitação Geriátrica'),
('Dra. Juliana Cardoso', 'juliana.cardoso@gmail.com', 'Fonoaudióloga em Comunicação Alternativa');

INSERT INTO curso (name, descricao, instrutor_id, photo) VALUES
('Curso de Fonoaudiologia', 'Curso de Fonoaudiologia com ênfase em Linguística', 1, '/images/fonoaudiologia.jpg'),
('Curso de Medicina', 'Curso de Medicina com ênfase em Cirurgia', 2, null),
('Curso de Terapia Ocupacional', 'Curso de Terapia Ocupacional com ênfase em Pediatria', 3, null),
('Curso de Fisioterapia', 'Curso de Fisioterapia com ênfase em Reabilitação', 4, null),
('Fonoaudiologia em Processamento Auditivo', 'Curso sobre PAC', 5, null),
('Medicina em Cardiologia', 'Curso sobre cardiologia aplicada à neurologia', 6, null),
('Terapia Ocupacional em Saúde Mental', 'Curso sobre saúde mental', 7, null),
('Fisioterapia em Reabilitação Neurológica', 'Curso sobre reabilitação neurológica', 8, null),
('ABA para Autismo', 'Curso introdutório sobre ABA para autistas', 9, null),
('ABA Avançado', 'Curso avançado de ABA para profissionais', 10, null),
('Psicologia Cognitiva', 'Curso sobre processos cognitivos e reabilitação', 11, null),
('Psicologia em Neurociências', 'Curso sobre fundamentos de neurociências', 12, null),
('Fonoaudiologia Infantil', 'Curso sobre linguagem infantil e distúrbios', 13, null),
('Fonoaudiologia Escolar', 'Curso sobre atuação do fonoaudiólogo em escolas', 14, null),
('Fisioterapia em Doenças Neuromusculares', 'Curso sobre fisioterapia em doenças neuromusculares', 15, null),
('Fisioterapia em AVC', 'Curso sobre reabilitação pós-AVC', 16, null),
('Disfagia Neurológica', 'Curso sobre avaliação e tratamento da disfagia', 17, null),
('Motricidade Orofacial', 'Curso sobre motricidade orofacial em neurologia', 18, null),
('ABA para Deficiência Intelectual', 'Curso sobre ABA aplicada à deficiência intelectual', 19, null),
('ABA para Inclusão Escolar', 'Curso sobre ABA para inclusão de alunos', 20, null),
('Psicologia do Desenvolvimento', 'Curso sobre desenvolvimento neuropsicológico', 21, null),
('Psicologia Infantil', 'Curso sobre psicologia aplicada à infância', 22, null),
('TO em Paralisia Cerebral', 'Curso sobre terapia ocupacional em paralisia cerebral', 23, null),
('TO em Reabilitação Física', 'Curso sobre reabilitação física em adultos', 24, null),
('Fisioterapia em Reabilitação Infantil', 'Curso sobre reabilitação infantil', 25, null),
('Fisioterapia em Reabilitação Motora', 'Curso sobre fisioterapia motora', 26, null),
('Disfagia em Adultos', 'Curso sobre disfagia em adultos com lesão neurológica', 27, null),
('Fonoaudiologia em Apraxia', 'Curso sobre apraxia de fala', 28, null),
('Neurodesenvolvimento', 'Curso sobre avaliação do neurodesenvolvimento', 29, null),
('Estimulação Cognitiva', 'Curso sobre técnicas de estimulação cognitiva', 30, null),
('TO em Reabilitação Cognitiva', 'Curso sobre reabilitação cognitiva', 31, null),
('TO em Lesão Cerebral', 'Curso sobre terapia ocupacional em lesão cerebral', 32, null),
('Fisioterapia Motora Avançada', 'Curso sobre técnicas avançadas em fisioterapia motora', 33, null),
('Fisioterapia Vestibular', 'Curso sobre reabilitação vestibular', 34, null),
('Processamento Auditivo Central', 'Curso sobre avaliação e intervenção em PAC', 35, null),
('Fonoaudiologia em Voz Neurológica', 'Curso sobre voz em pacientes neurológicos', 36, null),
('ABA para Professores', 'Curso sobre ABA para formação de professores', 37, null),
('ABA para Famílias', 'Curso sobre ABA para orientação familiar', 38, null),
('Psicologia em TEA', 'Curso sobre psicologia aplicada ao TEA', 39, null),
('Psicologia em Saúde Mental', 'Curso sobre saúde mental em neurologia', 40, null),
('TO em Deficiência Intelectual', 'Curso sobre inclusão e reabilitação', 41, null),
('TO em Saúde Mental', 'Curso sobre terapia ocupacional em saúde mental', 42, null),
('Fisioterapia em Reabilitação Motora', 'Curso sobre reabilitação motora', 43, null),
('Fisioterapia em Reabilitação Pós-AVC', 'Curso sobre fisioterapia pós-AVC', 44, null),
('Fonoaudiologia em Disartria', 'Curso sobre avaliação e tratamento da disartria', 45, null),
('Fonoaudiologia em Deglutição', 'Curso sobre deglutição em pacientes neurológicos', 46, null),
('Psicologia em Neuropsicopedagogia', 'Curso sobre neuropsicopedagogia', 47, null),
('Psicologia em Neurociência do Comportamento', 'Curso sobre neurociência do comportamento', 48, null),
('TO em Reabilitação Visual', 'Curso sobre reabilitação visual', 49, null),
('TO em Inclusão Escolar', 'Curso sobre inclusão escolar', 50, null),
('Fisioterapia em Reabilitação Geriátrica', 'Curso sobre fisioterapia em idosos', 51, null),
('Fisioterapia em Reabilitação Cognitiva', 'Curso sobre reabilitação cognitiva', 52, null),
('Fonoaudiologia em Linguagem Infantil', 'Curso sobre linguagem infantil', 53, null),
('Fonoaudiologia em Apraxia de Fala', 'Curso sobre apraxia de fala', 54, null),
('Psicologia em Neurociência', 'Curso sobre fundamentos de neurociência', 55, null),
('Psicologia em Estimulação Cognitiva', 'Curso sobre estimulação cognitiva', 56, null),
('TO em TEA', 'Curso sobre terapia ocupacional em TEA', 57, null),
('TO em Saúde Mental Infantil', 'Curso sobre saúde mental infantil', 58, null),
('Fisioterapia em Reabilitação Vestibular', 'Curso sobre reabilitação vestibular', 59, null),
('Fisioterapia em Reabilitação Pós-AVC', 'Curso sobre fisioterapia pós-AVC', 60, null),
('Fonoaudiologia em Comunicação Alternativa', 'Curso sobre comunicação alternativa', 61, null),
('Fonoaudiologia em Disfemia', 'Curso sobre disfemia', 62, null),
('Psicologia em Neuropsicologia Infantil', 'Curso sobre neuropsicologia infantil', 63, null),
('Psicologia em ABA para Autismo', 'Curso sobre ABA para autismo', 64, null),
('TO em Reabilitação Motora', 'Curso sobre reabilitação motora', 65, null),
('TO em Lesão Cerebral', 'Curso sobre lesão cerebral', 66, null),
('Fisioterapia em Doenças Degenerativas', 'Curso sobre doenças degenerativas', 67, null),
('Fisioterapia em Reabilitação Cognitiva', 'Curso sobre reabilitação cognitiva', 68, null),
('Fonoaudiologia em Processamento Auditivo', 'Curso sobre PAC', 69, null),
('Fonoaudiologia em Voz Neurológica', 'Curso sobre voz neurológica', 70, null),
('Psicologia em Estimulação Cognitiva', 'Curso sobre estimulação cognitiva', 71, null),
('Psicologia em Neurodesenvolvimento', 'Curso sobre neurodesenvolvimento', 72, null),
('TO em Inclusão Escolar', 'Curso sobre inclusão escolar', 73, null),
('TO em TEA', 'Curso sobre TEA', 74, null),
('Fisioterapia em Reabilitação Motora', 'Curso sobre reabilitação motora', 75, null),
('Fisioterapia em Reabilitação Pós-AVC', 'Curso sobre fisioterapia pós-AVC', 76, null),
('Fonoaudiologia em Processamento Auditivo Central', 'Curso sobre PAC', 77, null),
('Fonoaudiologia em Comunicação Alternativa', 'Curso sobre comunicação alternativa', 78, null),
('Psicologia em Neuropsicopedagogia', 'Curso sobre neuropsicopedagogia', 79, null),
('Psicologia em Neurociência do Comportamento', 'Curso sobre neurociência do comportamento', 80, null),
('TO em Saúde Mental', 'Curso sobre saúde mental', 81, null),
('TO em Deficiência Intelectual', 'Curso sobre deficiência intelectual', 82, null),
('Fisioterapia em Reabilitação Geriátrica', 'Curso sobre fisioterapia geriátrica', 83, null),
('Fisioterapia em Reabilitação Cognitiva', 'Curso sobre reabilitação cognitiva', 84, null),
('Fonoaudiologia em Linguagem Infantil', 'Curso sobre linguagem infantil', 85, null),
('Fonoaudiologia em Apraxia de Fala', 'Curso sobre apraxia de fala', 86, null),
('Psicologia em Neuropsicologia', 'Curso sobre neuropsicologia', 87, null),
('Psicologia em ABA para Deficiência Intelectual', 'Curso sobre ABA para deficiência intelectual', 88, null),
('TO em Reabilitação Visual', 'Curso sobre reabilitação visual', 89, null),
('TO em Inclusão Escolar', 'Curso sobre inclusão escolar', 90, null),
('Fisioterapia em Reabilitação Motora', 'Curso sobre reabilitação motora', 91, null),
('Fisioterapia em Reabilitação Pós-AVC', 'Curso sobre fisioterapia pós-AVC', 92, null),
('Fonoaudiologia em Processamento Auditivo Central', 'Curso sobre PAC', 93, null),
('Fonoaudiologia em Comunicação Alternativa', 'Curso sobre comunicação alternativa', 94, null),
('Psicologia em Neurodesenvolvimento', 'Curso sobre neurodesenvolvimento', 95, null),
('Psicologia em Estimulação Cognitiva', 'Curso sobre estimulação cognitiva', 96, null),
('TO em TEA', 'Curso sobre terapia ocupacional em TEA', 97, null),
('TO em Saúde Mental', 'Curso sobre saúde mental', 98, null);